export { AgentRole, AGENT_ROLES, type AgentRoleType } from './agents.js';
export {
  EvtEventSchema,
  EvtSourceSchema,
  EvtActorSchema,
  EvtScopeSchema,
  BACKOFFICE_EVENT_TYPES,
  createBackofficeEvent,
  type EvtEvent,
  type EvtSource,
  type EvtActor,
  type EvtScope,
  type EvtQueryParams,
  type EvtQueryResult,
  type BackofficeEventType,
} from './events.js';
export {
  RBACConfigSchema,
  RBACGroupConfigSchema,
  ServicePermissionSchema,
  ProcessConfigSchema,
  CompanyConfigSchema,
  PerCompanyRBACConfigSchema,
  resolvePermissions,
  resolveCompanyAccess,
  resolveAccessibleCompanies,
  canApprove,
  type RBACConfig,
  type RBACGroupConfig,
  type ServicePermission,
  type ProcessConfig,
  type CompanyConfig,
  type PerCompanyRBACConfig,
  type ResolvedAccess,
} from './rbac.js';
